### ISSUE TITLE
log.fs Windows compatibility 

### ISSUE THREAD

**Issue by IDerr** [adaltas/node-nikita#112]
When you launch ryba-env for the first time on windows, it tries to create the log/cache directory, but can't because of the split (check below), it'll be better to split by path.sep.
But if we are trying to create a folder on the remote host, it'll use the path.sep on the host which launch ryba no ?
nikita/system/mkdir:83
```
directories = directory.split('/')
```

**Comment by wdavidw** [comment]
ok, but the logic is as follow, if ssh is null, then use path.sep, if ssh isnt null, then use path.posix.sep

**Comment by wdavidw** [comment]
i'll let you do it!

**Comment by IDerr** [comment]
Ok, thanks :)

**Comment by wdavidw** [comment]
any progress ?

**Comment by IDerr** [comment]
This issue is no longer valid, since rewrite.
