### ISSUE TITLE
tools.repo gpg verify need tests and clarification

### ISSUE THREAD

**Issue by wdavidw** [adaltas/node-nikita#113]
@lucasbak , I cant understand what you wish to accomplish with the gpg keys. The [test associated with the verify option](
https://github.com/adaltas/node-nikita/blob/master/test/tools/repo.coffee#L103-L131) test nothing. Please clarify or remove this test.

**Comment by wdavidw** [comment]
@lucasbak please review above commit, also focus on how options must be documented (usage of tild, spaces...)

**Comment by lucasbak** [comment]
has reviewed it and works as it should.
Good to close it

**Comment by wdavidw** [comment]
great
