### ISSUE TITLE
tools.dconf: tests are not passing

### ISSUE THREAD

**Issue by sergkudinov** [adaltas/node-nikita#185]
Tests of `tools.dconf` are not passing.

When running this:
```
nikita
  ssh: ssh
, ->
  @tools.dconf
    properties:
      '/org/gnome/desktop/datetime/automatic-timezone': false
```

It is setting a key (`dconf write /org/gnome/desktop/datetime/automatic-timezone "false"`), what leads to an error:
```
error: Cannot autolaunch D-Bus without X11 $DISPLAY
```

### Possible solution:
It is required to start a session bus instance (locally and remotely) of *dbus-daemon* before `dconf write`:
```
export $(dbus-launch)
dconf write /org/gnome/desktop/datetime/automatic-timezone "false"
```
or like this:
```
dbus-launch dconf write /org/gnome/desktop/datetime/automatic-timezone "false"
```

### To reproduce:
```
cd packages/tools/env/dconf
docker-compose up --abort-on-container-exit
```

**Comment by wdavidw** [comment]
Fixed with 27cdd46b1ed919bb32da3cc0a2c79d6ed2b6ea11
