### ISSUE TITLE
Mocha doesn't catch errors when register actions

### ISSUE THREAD

**Issue by sergkudinov** [adaltas/node-nikita#210]
This issue is descovered when fixing an error in [this commit](https://github.com/adaltas/node-nikita/commit/384ef90e15fae7f27d208b31096dc39255772adb).

**Comment by sergkudinov** [comment]
@wdavidw Can you describe this error please in more details just to remember? I might be wrong if I do.

**Comment by wdavidw** [comment]
Mocha swallow any error when the registry register actions.

**Comment by sergkudinov** [comment]
Closed with https://github.com/adaltas/node-nikita/pull/211
