### ISSUE TITLE
website: broken layout on pages with embed code snippets

### ISSUE THREAD

**Issue by sergkudinov** [adaltas/node-nikita#295]
The `gatsby-remark-embed-snippet` Gatsby plugin breaks html-dom.

## To reproduce

Run `cd docs/website && yarn develop` and go to http://localhost:8000/current/about/tutorial/

The error in console:
```
Warning: validateDOMNesting(...): <pre> cannot appear as a descendant of <p>.
```

**Comment by wdavidw** [comment]
Simply remove the usage of `gatsby-remark-embed-snippet`, it was already requested a few weeks ago
