### ISSUE TITLE
not able to run docs site 

### ISSUE THREAD

**Issue by shivaylamba** [adaltas/node-nikita#382]
**Describe the bug**

I am trying to run the nikitajs docs site locally in my system by following the instructions provided in the Readme section for the docs-website. I run into the following error when trying to run` yarn serve` command

`(base) ➜  website git:(master) yarn serve
yarn run v1.22.17
$ gatsby serve
failed We've encountered an error: Minified React error #31; visit https://react
js.org/docs/error-decoder.html?invariant=31&args[]=Error%3A%20ENOENT%3A%20no%20s
uch%20file%20or%20directory%2C%20open%20'%2FUsers%2Fshivaylamba%2FDesktop%2Ffina
l-test-gatsby%2Fnikita%2Fdocs%2Fwebsite%2F.cache%2Fmatch-paths.json'&args[]= for
 the full message or use the non-minified dev environment for full errors and
additional helpful warnings.`

**Additional context**

I am using MacOS on an Apple mac M1 chip. 

**Steps to Reproduce**

Follow the following steps mentioned in the link to install and run the docs website: 
https://github.com/adaltas/node-nikita/blob/master/docs/website/README.md

**Comment by shivaylamba** [comment]
@wdavidw

**Comment by wdavidw** [comment]
Could you try again now, following the docs/website/README.md instructions. I shall work again.

**Comment by shivaylamba** [comment]
Ok I will test it and let you know

**Comment by wdavidw** [comment]
Hi @shivaylamba, just a quick followup. Did you manage to make it work ?

**Comment by shivaylamba** [comment]
Hi @wdavidw yes it did work! Thank you

**Comment by wdavidw** [comment]
Good news. Closing then.
