### ISSUE TITLE
bug(tests): lxd.network and lxd.file.push tests don't pass

### ISSUE THREAD

**Issue by kellianoy** [adaltas/node-nikita#385]
**Describe the bug**

Running tests inside of lxc.network result in them failing. 

```
lxc.network.create
       Create a new network (local):
     Error: NIKITA_EXECUTE_EXIT_CODE_INVALID: an unexpected exit code was encountered, command is "lxc network list --format csv | grep nkt-network-2…", got 1 instead of {"true":[0],"false":[42]}.
      at Object.module.exports [as error] (/home/kellian/Documents/nikita/packages/core/lib/utils/error.js:36:10)
      at Immediate.<anonymous> (/home/kellian/Documents/nikita/packages/core/lib/actions/execute/index.js:722:31)
      at processImmediate (node:internal/timers:466:21)
```

**Additional context**

OS: NixOS

The tests also fail in lxc.file.push. They try to install a package, but there is no network so the package can't be resolved. Adding the network, I saw that they failed too.

**Steps to Reproduce**

* Clone Nikita main branch,
* Run `yarn install`,
* Select the tests you want to run using `they.only` inside of `packages/lxd/src/network`, for instance `lxc.network.create: Create a new network` inside of `index.coffee`
* Run tests using `yarn test` or `npm test`

**Example Project**

```coffee
they 'Create a new network', ({ssh}) ->
    nikita
      $ssh: ssh
    , ({registry}) ->
      await registry.register 'clean', ->
        @lxc.network.delete
          network: "nkt-network-2"
      try
        await @clean()
        {$status} = await @lxc.network
          network: "nkt-network-2"
        $status.should.be.true()
      finally
        await @clean()
```

**Current bug behavior**

Tests fail.

**Expected correct behavior**

Tests run successfully.

**Comment by wdavidw** [comment]
Considering that the tests are ok with LXD 4.24 installed on Ubuntu, we will need more details such as the LXD version and the exact command which fails.

**Comment by kellianoy** [comment]
My LXD version is 5.0.0, so it is most likely the cause of this. However I can't downgrade because the compatibility with virtual machines will break if I do.

It seems weird because I still can use the functionalities correctly outside of the test suite, though. Tests should pass correctly according to this.

The command that fails is, as I said, `npm test` with the 'Create a new network` test as "they.only" in 'lxd/cluster/index.coffee.md`.

**Comment by wdavidw** [comment]
`lxc.network` as well as `lxc.network.delete` are using commands instead of `lxc.query`. We shall update those commands. Looking at your error, it seems to be thrown by `lxc.network.delete`, try running `lxc network list --format csv` but, again, we shall use `lxc.network.list` which internally uses `lxc.query`.

**Comment by wdavidw** [comment]
`lxc.network.delete` is not using `lxc.query` and we shall use it.
