### ISSUE TITLE
service file render windows

### ISSUE THREAD

**Issue by IDerr** [adaltas/node-nikita#83]
When the project is cloned on windows, line endings are "\r\n", 
so when nikita renders the service file, it makes an unexecutable service like this :  

https://gist.github.com/IDerr/1d4bbff96468f22532427575db1c88a7

I bypassed that by adding
```js
content = content.replace(/(\r\n|\r)$/gm,"\n")
```
on render.js:28

Not pretty but working.

**Comment by wdavidw** [comment]
> When the project is cloned on windows, line endings are "\r\n",

If, as u write, u get windows style file ending when u clone the project, then it seems like this is a misconfiguration of your git client, look at the "autocrlf=input" setting.

**Comment by IDerr** [comment]
https://help.github.com/articles/dealing-with-line-endings/
https://github.com/heroku/cli/blob/master/.gitattributes

To avoid an another issue like this, we should add a .gitattributes like the file above
